// Nivel 0 — Modelo mental (8 skills). Autoría única por skill, trilingüe en núcleo.
import { sk } from './base.mjs';

export const L0 = [
  sk(0, 0, {
    t: { es: 'Modelo de empresa', en: 'Company model', de: 'Unternehmensmodell' },
    o: { es: 'Explicar cómo SAP B1 estructura una empresa y qué implica cada decisión estructural.', en: 'Explain how SAP B1 structures a company and what each structural decision implies.', de: 'Erklären, wie SAP B1 ein Unternehmen strukturiert und was jede Strukturentscheidung bedeutet.' },
    c: { es: 'Una base de datos SAP B1 contiene una sociedad con sus datos maestros, configuración y documentos; desde 10.0, sucursales (branches) permiten separar balances dentro de la misma sociedad.', en: 'One SAP B1 database holds one company with its master data, configuration, and documents; since 10.0, branches separate balance reporting inside the same company.', de: 'Eine Datenbank enthält eine Firma mit Stammdaten, Konfiguration und Belegen; seit 10.0 trennen Branchen die Bilanz innerhalb der Firma.' },
    m: { es: 'Piensa «estructura primero»: cada pantalla que ves vive dentro de decisiones estructurales tomadas antes.', en: 'Think «structure first»: every screen you see lives inside structural decisions made before.' },
    p: { es: 'Dibuja SYN-COMPANY: sociedad, sucursales y para qué serviría una segunda base de datos.', en: 'Sketch SYN-COMPANY: company, branches, and when a second database would be justified.', de: 'Skizziere SYN-COMPANY: Firma, Branchen und wann eine zweite Datenbank sinnvoll wäre.' },
    v: { es: 'Verifica qué comparten y qué separan sociedad y sucursal antes de proponer cambios.', en: 'Verify what company and branch share versus separate before proposing changes.', de: 'Prüfe, was Firma und Zweigstelle teilen bzw. trennen, bevor du Änderungen vorschlägst.' },
    vs: [{ es: 'Identifica la sociedad activa', en: 'Identify the active company' }, { es: 'Lista las sucursales y su propósito', en: 'List branches and their purpose' }, { es: 'Marca qué datos son globales y cuáles por sucursal', en: 'Mark which data is global vs per-branch' }],
    r: { es: 'No asumas multi-sociedad donde solo hay sucursales: rompe reportes y autorizaciones.', en: 'Do not assume multi-company where only branches exist: it breaks reports and authorizations.', de: 'Nicht Multi-Company annehmen, wo nur Branchen existieren: Das bricht Berichte und Berechtigungen.' },
    tips: { es: ['El nombre de la sociedad aparece en cada documento imprimible: errores aquí se ven fuera.', 'Sucursales comparten artícos y socios, pero separan finanzas.'], en: ['The company name appears on every printable document: mistakes here are visible outside.', 'Branches share items and partners but separate finances.'] },
    pf: { es: 'Crear una segunda base de datos para separar líneas de negocio cuando las sucursales bastan.', en: 'Creating a second database to separate business lines when branches suffice.' },
    d: { k: 'tree', cap: { es: 'Sociedad → sucursales → documentos', en: 'Company → branches → documents' }, n: [{ t: 'Sociedad', s: 'DB única' }, { t: 'Sucursal NORTE', s: 'finanzas propias' }, { t: 'Sucursal SUR', s: 'finanzas propias' }, { t: 'Documentos', s: 'marcados por sucursal' }] },
    a: {
      prompt: { es: 'SYN pide separar dos almacenes con contabilidad independiente en la misma sociedad legal. ¿Qué estructura aplicas?', en: 'SYN needs two warehouses with independent accounting inside the same legal company. Which structure applies?', de: 'SYN braucht zwei Lager mit getrennter Buchhaltung in derselben Firma. Welche Struktur passt?' },
      opts: { es: ['Sucursales (branches) dentro de la misma base de datos', 'Dos bases de datos SAP B1 separadas', 'Dos carpetas en el mismo almacén'], en: ['Branches inside the same database', 'Two separate SAP B1 databases', 'Two folders in the same warehouse'], de: ['Branchen in derselben Datenbank', 'Zwei getrennte Datenbanken', 'Zwei Lagerordner im selben Lager'] },
      correct: 0,
      why: { es: 'Las sucursales separan la contabilidad dentro de una sociedad legal sin duplicar datos maestros ni licencias; dos bases de datos se reservan para sociedades legales distintas.', en: 'Branches separate accounting inside one legal company without duplicating master data or licences; separate databases are for distinct legal entities.', de: 'Branchen trennen die Buchhaltung innerhalb einer Firma, ohne Stammdaten zu duplizieren; getrennte Datenbanken sind für eigene Rechtsträger.' },
      prin: [{ es: 'Mínima estructura que cumple', en: 'Smallest structure that complies' }, { es: 'Un sistema, una verdad', en: 'One system, one truth' }, { es: 'Duplicar por seguridad', en: 'Duplicate for safety' }], prinOk: 0,
      senior: [{ es: 'Pregunta primero por la razón legal, no por la operación', en: 'Ask for the legal reason first, not operations' }, { es: 'Contrasta lo que comparten las sucursales (maestros) con lo que separan (finanzas)', en: 'Contrast what branches share (masters) vs separate (finance)' }, { es: 'Elige la estructura menor y deja constancia de la decisión', en: 'Pick the smaller structure and record the decision' }],
      dwhy: { es: ['Dos bases de datos duplican maestros, rompen la vista consolidada y duplican coste de infraestructura y conciliación.', 'Las carpetas solo separan ubicación física; no tocan contabilidad ni balances.', 'Duplicar sistemas agrava el problema: ahora hay dos verdades que reconciliar a mano.'], en: ['Two databases duplicate masters, break consolidated view, and double infrastructure and reconciliation cost.', 'Folders only separate physical location; they touch neither accounting nor balances.', 'Duplicating systems worsens it: now two truths need manual reconciliation.'], de: ['Zwei Datenbanken duplizieren Stammdaten und brechen die Konsolidierung.', 'Ordner trennen nur den physischen Ort, nicht die Buchhaltung.', 'Systemduplikation erzeugt zwei Wahrheiten für manuelle Abstimmung.'] },
      hints: { es: '¿La separación que piden es legal-contable o solo organizativa?' }
    }
  }),
  sk(0, 1, {
    t: { es: 'Cliente de escritorio y Web Client', en: 'Desktop client and Web Client', de: 'Desktop-Client und Web Client' },
    o: { es: 'Distinguir qué hace cada cliente SAP B1 y elegir el adecuado por tarea.', en: 'Distinguish what each SAP B1 client does and pick the right one per task.', de: 'Unterscheiden, was jeder Client kann, und ihn je Aufgabe wählen.' },
    c: { es: 'El cliente de escritorio cubre el alcance funcional completo (configuración incluida); el Web Client (desde 10.0) cubre procesos operativos core en navegador con despliegue y acceso moderno; la paridad NO es total.', en: 'The desktop client covers the full functional scope (configuration included); the Web Client (from 10.0) covers core operational processes in the browser with modern access; parity is NOT total.', de: 'Der Desktop-Client deckt den vollen Funktionsumfang ab; der Web Client (ab 10.0) deckt Kernprozesse im Browser ab — Parität besteht nicht vollständig.' },
    m: { es: 'Cada cliente tiene un terreno: pregunta siempre «¿esta tarea existe en Web o es de escritorio?»', en: 'Each client owns terrain: always ask «does this task exist in Web or is it desktop-only?»', },
    p: { es: 'Clasifica diez tareas SYN en escritorio/Web/ambos y marca las que dudarías.', en: 'Classify ten SYN tasks into desktop/Web/both and mark the doubtful ones.', de: 'Ordne zehn SYN-Aufgaben Desktop/Web/beiden zu und markiere Zweifel.' },
    v: { es: 'Comprueba la versión y el feature package antes de afirmar paridad.', en: 'Check version and feature package before claiming parity.', de: 'Prüfe Version und Feature Package, bevor du Parität behauptest.' },
    vs: [{ es: 'Lista la tarea y su módulo', en: 'List the task and its module' }, { es: 'Busca soporte oficial por versión', en: 'Check official support per version' }, { es: 'Decide cliente y déjalo escrito', en: 'Decide the client and document it' }],
    r: { es: 'Afirmar «el Web hace todo» sin verificar versión produce incidencias evitables.', en: 'Claiming «Web does everything» without verifying version creates avoidable incidents.', de: '„Der Web Client kann alles“ ohne Versionsprüfung erzeugt vermeidbare Störungen.' },
    tips: { es: ['La configuración profunda (G/L determination, autorizaciones finas) sigue siendo terreno de escritorio.', 'Usa el Web Client como criterio de modernización de procesos, no como clon.'], en: ['Deep configuration (G/L determination, fine authorizations) remains desktop territory.', 'Treat the Web Client as a process-modernization lever, not a clone.'] },
    pf: { es: 'Prometer una migración total a Web sin inventario de funcionalidades usadas.', en: 'Promising a full Web migration without an inventory of used features.' },
    d: { k: 'matrix', cap: { es: 'Alcance por cliente', en: 'Scope per client' }, n: [{ t: 'Configuración', s: 'escritorio' }, { t: 'Operativa diaria', s: 'ambos' }, { t: 'Acceso remoto moderno', s: 'Web' }, { t: 'Paridad total', s: 'NO' }] },
    a: {
      prompt: { es: 'El equipo SYN quiere «trabitar todo en navegador ya». ¿Qué responde un consultor serio?', en: 'The SYN team wants «everything in the browser now». What does a serious consultant answer?', de: 'Das SYN-Team will „alles im Browser“. Was antwortet ein seriöser Berater?' },
      opts: { es: ['Inventario de procesos por cliente + hoja de ruta por versión', 'Migrar todo de golpe al Web Client', 'Prohibir el navegador por seguridad'], en: ['Inventory processes per client + a version-based roadmap', 'Migrate everything to Web Client at once', 'Ban the browser for security'], de: ['Prozessinventar je Client + Versionfahrplan', 'Alles auf einmal in den Web Client', 'Browser aus Sicherheitsgründen verbieten'] },
      correct: 0,
      why: { es: 'La paridad depende de la versión: el inventario por proceso y la hoja de ruta evitan prometer lo que la versión no da.', en: 'Parity depends on version: a per-process inventory and roadmap avoid promising what the version does not deliver.', de: 'Parität hängt von der Version ab: Inventar und Fahrplan verhindern leere Versprechen.' },
      prin: [{ es: 'Verificar versión antes de prometer', en: 'Verify version before promising' }, { es: 'Modernizar de golpe', en: 'Modernize in one leap' }, { es: 'Restringir por miedo', en: 'Restrict out of fear' }], prinOk: 0,
      senior: [{ es: 'Pide la lista de procesos reales del equipo, no el deseo', en: 'Ask for the team’s real process list, not the wish' }, { es: 'Contrasta cada proceso con la matriz de alcance de la versión instalada', en: 'Contrast each process with the installed version’s scope matrix' }, { es: 'Entrega ruta por fases con criterios medibles', en: 'Deliver a phased route with measurable criteria' }],
      dwhy: { es: ['Migrar todo de golpe asume paridad inexistente: los huecos aparecen en producción.', 'Prohibir el navegador tira por la borda el beneficio real del Web Client sin eliminar riesgo.', 'El inventario es el único camino que convierte una opinión en un plan verificable.'], en: ['Migrating everything at once assumes nonexistent parity: gaps surface in production.', 'Banning the browser discards the Web Client’s real benefit without removing risk.', 'The inventory is the only path that turns opinion into a verifiable plan.'], de: ['Alles auf einmal setzt fehlende Parität voraus: Lücken erscheinen im Betrieb.', 'Browserverbot verwirft den echten Nutzen ohne Risikoabbau.', 'Nur das Inventar macht die Meinung prüfbar.'] },
      hints: { es: '¿Qué sabes de la paridad real sin mirar la versión instalada?' }
    }
  }),
  sk(0, 2, {
    t: { es: 'Módulos y responsabilidades', en: 'Modules and responsibilities', de: 'Module und Verantwortlichkeiten' },
    o: { es: 'Maprear los módulos de SAP B1 sobre procesos de negocio con dueños claros.', en: 'Map SAP B1 modules onto business processes with clear owners.', de: 'Module auf Geschäftsprozesse mit klaren Eigentümern abbilden.' },
    c: { es: 'Compras, Ventas, CRM, Inventario, Producción, MRP, Servicio, Finanzas, Bancos y Recursos Humanos comparten una sola base de datos: lo que uno contabiliza lo heredan todos.', en: 'Purchasing, Sales, CRM, Inventory, Production, MRP, Service, Finance, Banking, and HR share one database: what one module posts, all inherit.', de: 'Einkauf, Verkauf, CRM, Lager, Produktion, MRP, Service, Finanzen, Bank und HR teilen eine Datenbank.' },
    m: { es: 'Sigue el dato, no el menú: los módulos son vistas de una única corriente documental.', en: 'Follow the data, not the menu: modules are views of one document stream.', },
    p: { es: 'Asigna cada proceso SYN a un módulo dueño y a un módulo afectado.', en: 'Assign each SYN process to an owning module and an affected module.', de: 'Ordne jeden SYN-Prozess einem Owner-Modul und einem betroffenen Modul zu.' },
    v: { es: 'Comprueba que cada efecto cruzado (stock→contabilidad) tiene dueño en ambos lados.', en: 'Verify every cross effect (stock→accounting) has an owner on both sides.', de: 'Prüfe, dass jede Quell-Wirkung auf beiden Seiten einen Eigentümer hat.' },
    vs: [{ es: 'Nombra el proceso de negocio', en: 'Name the business process' }, { es: 'Asigna módulo dueño', en: 'Assign the owning module' }, { es: 'Traza efectos en otros módulos', en: 'Trace effects into other modules' }],
    r: { es: 'Un cambio «local» de módulo puede mover cuentas ajenas: nadie es isla en B1.', en: 'A «local» module change can move foreign accounts: no module is an island.', de: 'Eine „lokale“ Moduländerung kann fremde Konten bewegen.' },
    tips: { es: ['El 80% de las incidencias de un módulo nacen en la configuración de otro.', 'Designa dueños por proceso, no por pantalla.'], en: ['80% of a module’s incidents are born in another module’s configuration.', 'Assign owners by process, not by screen.'] },
    pf: { es: 'Optimizar Ventas sin mirar el efecto en Finanzas y Stock.', en: 'Optimizing Sales without looking at Finance and Inventory effects.' },
    d: { k: 'hub', cap: { es: 'Una base de datos, muchos módulos', en: 'One database, many modules' }, n: [{ t: 'Ventas', s: 'documentos' }, { t: 'Finanzas', s: 'asientos' }, { t: 'Stock', s: 'movimientos' }, { t: 'UNA DB', s: 'centro' }] },
    a: {
      prompt: { es: 'Ventas SYN pide cambiar la lista de precios por defecto. ¿A quién avías antes de aprobar?', en: 'SYN Sales asks to change the default price list. Whom do you notify before approving?', de: 'Der Verkauf will die Standardpreisliste ändern. Wen informierst du vorher?' },
      opts: { es: ['A los dueños de margen y finanzas, porque cambia precios efectivos de futuros documentos', 'A nadie: es una pantalla de Ventas', 'Solo al equipo técnico'], en: ['Margin and finance owners, because effective prices of future documents change', 'Nobody: it’s a Sales screen', 'Only the technical team'], de: ['Margen- und Finanzverantwortliche, weil effektive Preise künftiger Belege sich ändern', 'Niemanden: ein Verkaufsbild', 'Nur das technische Team'] },
      correct: 0,
      why: { es: 'La lista por defecto contamina cada documento nuevo: el efecto es de margen y contabilidad, no solo comercial.', en: 'The default list seeds every new document: the effect hits margin and accounting, not just sales.', de: 'Die Standardliste steuert jeden neuen Beleg: Wirkung auf Marge und Buchhaltung.' },
      prin: [{ es: 'Seguir el efecto, no la pantalla', en: 'Follow the effect, not the screen' }, { es: 'Pantalla = propiedad', en: 'Screen = ownership' }, { es: 'Primero técnico, luego negocio', en: 'Technical first, business later' }], prinOk: 0,
      senior: [{ es: 'Traza la configuración hasta el documento que la hereda', en: 'Trace the config down to the document inheriting it' }, { es: 'Identifica quién mide el impacto (margen, finanzas)', en: 'Identify who measures the impact (margin, finance)' }, { es: 'Pide validación con un documento de prueba', en: 'Request validation with a test document' }],
      dwhy: { es: ['«Es de Ventas» ignora que finanzas hereda el precio en el asiento del futuro documento.', 'Avisar solo al equipo técnico deja al dueño del margen fuera de la decisión.', 'Nadie mide el impacto real → sorpresas en el cierre de mes.'], en: ['«It’s Sales» ignores that finance inherits the price in future documents’ entries.', 'Notifying only tech leaves the margin owner out of the decision.', 'Nobody measures real impact → month-end surprises.'], de: ['„Verkaufssache“ ignoriert, dass die Finanzbuchhaltung den Preis erbt.', 'Nur Technik informieren schließt den Margin-Owner aus.', 'Ohne Messung kommen Monatsendschocks.'] },
      hints: { es: '¿Quién verá este cambio en su informe sin saber que existe?' }
    }
  }),
  sk(0, 3, {
    t: { es: 'Dato maestro frente a documento', en: 'Master data versus document', de: 'Stammdaten gegenüber Beleg' },
    o: { es: 'Separar con precisión qué gobierna el maestro y qué congela el documento.', en: 'Precisely separate what the master governs from what the document freezes.', de: 'Trennen, was der Stammsatz steuert und was der Beleg einfriert.' },
    c: { es: 'El dato maestro gobierna valores por defecto y comportamiento futuro; el documento copia lo que necesita en el momento y conserva su propio contexto para siempre.', en: 'Master data governs defaults and future behaviour; the document copies what it needs at that moment and keeps its own context forever.', de: 'Stammdaten steuern Vorgaben und Zukunft; der Beleg kopiert im Moment und bewahrt seinen Kontext.' },
    m: { es: 'Cambia el maestro para el futuro; nunca reescribas el pasado que el documento ya guardó.', en: 'Change the master for the future; never rewrite the past the document already stored.', },
    p: { es: 'Toma el socio SYN-BP-01: cambia su condición de pago y predice qué documentos cambian.', en: 'Take partner SYN-BP-01: change its payment term and predict which documents change.', de: 'Ändere bei SYN-BP-01 die Zahlungsbedingung und sage voraus, welche Belege sich ändern.' },
    v: { es: 'Comprueba en documentos existentes que nada retro-efectuó.', en: 'Verify on existing documents that nothing retro-effected.', de: 'Prüfe an Bestandsbelegen, dass nichts rückwirkend wirkte.' },
    vs: [{ es: 'Identifica el campo a cambiar', en: 'Identify the field to change' }, { es: 'Clasifica: maestro o documento', en: 'Classify: master or document' }, { es: 'Predice efecto en existentes vs futuros', en: 'Predict effect on existing vs future' }],
    r: { es: 'Los documentos históricos no cambian al cambiar el maestro; asumir lo contrario rompe auditorías.', en: 'Historical documents do not change when the master does; assuming otherwise breaks audits.', de: 'Historische Belegen ändern sich nicht mit dem Stammsatz.' },
    tips: { es: ['Piensa «fotografía vs regla»: el documento es fotografía; el maestro es regla.', 'Los informes mezclan ambos: pregunta siempre de qué lado viene cada columna.'], en: ['Think «snapshot vs rule»: the document is the snapshot; the master is the rule.', 'Reports mix both: always ask which side each column comes from.'] },
    pf: { es: 'Corregir un documento antiguo editando el maestro que lo originó.', en: 'Fixing an old document by editing the master that seeded it.' },
    d: { k: 'split', cap: { es: 'El maestro rige futuros; el documento congeló su instante', en: 'The master rules futures; the document froze its instant' }, n: [{ t: 'Maestro', s: 'regla viva' }, { t: 'Documentos futuros', s: 'heredan cambio' }, { t: 'Documentos pasados', s: 'intactos' }] },
    a: {
      prompt: { es: 'SYN sube el descuento del cliente SYN-BP-02. ¿Qué documentos reflejarán el nuevo descuento?', en: 'SYN raises the discount on partner SYN-BP-02. Which documents will reflect the new discount?', de: 'SYN erhöht den Rabatt bei SYN-BP-02. Welche Belegen zeigen ihn?' },
      opts: { es: ['Solo los documentos creados después del cambio', 'Todos, incluidos los históricos', 'Ninguno: hay que re-crearlos'], en: ['Only documents created after the change', 'All, including historical ones', 'None: they must be recreated'], de: ['Nur Belege nach der Änderung', 'Alle, auch historische', 'Keine: neu anlegen'] },
      correct: 0,
      why: { es: 'El descuento es valor por defecto del maestro: lo capturan los documentos nuevos; los históricos conservan su propia copia.', en: 'The discount is a master default: new documents capture it; historical ones keep their own copy.', de: 'Der Rabatt ist eine Stammvorgabe: neue Belegen erfassen ihn; historische behalten ihre Kopie.' },
      prin: [{ es: 'Fotografía vs regla', en: 'Snapshot vs rule' }, { es: 'Regla retroactiva', en: 'Retroactive rule' }, { es: 'Reconstrucción manual', en: 'Manual rebuild' }], prinOk: 0,
      senior: [{ es: 'Confirma que el descuento vive en el maestro, no en un acuerdo aparte', en: 'Confirm the discount lives in the master, not a separate agreement' }, { es: 'Define la fecha de corte: documentos desde cuándo', en: 'Define the cut date: documents from when' }, { es: 'Comunica la fecha de corte al equipo comercial', en: 'Communicate the cut date to sales' }],
      dwhy: { es: ['«Todos» confunde regla con fotografía: los históricos ya capturaron su valor.', 'Re-crear documentos destruye la trazabilidad y duplica asientos.', 'La respuesta correcta protege la auditoría: el pasado es inmutable.'], en: ['«All» confuses rule with snapshot: historical ones already captured their value.', 'Recreating documents destroys traceability and duplicates entries.', 'The correct answer protects auditability: the past is immutable.'], de: ['„Alle“ verwechselt Regel und Momentaufnahme.', 'Neuanlegen zerstört Nachvollziehbarkeit.', 'Richtig schützt die Prüfbarkeit: Vergangenheit ist unveränderlich.'] },
      hints: { es: '¿Qué guardó el documento en el momento de crearse?' }
    }
  }),
  sk(0, 4, {
    t: { es: 'Estados, series y trazabilidad', en: 'Statuses, series and traceability', de: 'Status, Serien und Nachvollziehbarkeit' },
    o: { es: 'Leer el ciclo de vida de un documento por sus estados y series sin abrirlo.', en: 'Read a document’s lifecycle from its statuses and series without opening it.', de: 'Den Lebenszyklus eines Belegs an Status und Nummernkreis lesen.' },
    c: { es: 'Cada documento avanza por estados (abierto, cerrado, cancelado) y pertenece a una serie de numeración que identifica su origen y periodo; la combinación estado+serie resume su historia.', en: 'Documents advance through statuses (open, closed, cancelled) and belong to a numbering series identifying origin and period; status+series summarizes its story.', de: 'Belege durchlaufen Status (offen, geschlossen, storniert) und gehören zu einem Nummernkreis.' },
    m: { es: 'Ante un documento desconocido: estado y serie primero, detalles después.', en: 'Facing an unknown document: status and series first, details later.', },
    p: { es: 'Ordena cinco documentos SYN por estado y detecta el cancelado por su serie.', en: 'Order five SYN documents by status and spot the cancelled one by its series.', de: 'Sortiere fünf SYN-Belege nach Status und finde den stornierten am Nummernkreis.' },
    v: { es: 'Confirma que la serie corresponde al tipo y periodo declarados.', en: 'Confirm the series matches the declared type and period.', de: 'Bestätige, dass der Kreis zu Typ und Periode passt.' },
    vs: [{ es: 'Lee estado del documento', en: 'Read the document status' }, { es: 'Identifica serie y periodo', en: 'Identify series and period' }, { es: 'Contrasta con el proceso esperado', en: 'Contrast with the expected process' }],
    r: { es: 'Cerrar o cancelar sin entender la diferencia destruye datos operativos: cerrar ≠ cancelar.', en: 'Closing or cancelling without understanding the difference destroys operational data: closed ≠ cancelled.', de: 'Schließen ≠ Stornieren: Unwissentlich zerstört das Bestandsdaten.' },
    tips: { es: ['Cerrado deja el documento visible pero sin cantidad abierta; cancelado lo anula con documento espejo.', 'Una serie por tipo de documento y año simplifica auditorías.'], en: ['Closed keeps the document visible with zero open quantity; cancelled voids it with a mirror document.', 'One series per document type and year simplifies audits.'] },
    pf: { es: 'Cancelar un pedido entregado parcialmente en vez de cerrarlo.', en: 'Cancelling a partially delivered order instead of closing it.' },
    d: { k: 'timeline', cap: { es: 'Vida de un documento: abierto → cerrado/cancelado', en: 'Document life: open → closed/cancelled' }, n: [{ t: 'Abierto', s: 'cantidad pendiente' }, { t: 'Cerrado', s: 'fin natural' }, { t: 'Cancelado', s: 'anulación espejo' }] },
    a: {
      prompt: { es: 'SYN-SO-0007 está entregado al 80% y el cliente cancela el resto. ¿Qué haces con el pedido?', en: 'SYN-SO-0007 is 80% delivered and the customer cancels the rest. What do you do with the order?', de: 'SYN-SO-0007 ist zu 80% geliefert, der Rest storniert. Was tun?' },
      opts: { es: ['Cerrar el pedido: deja lo entregado y libera el resto sin anular', 'Cancelar: anula también lo entregado', 'Dejarlo abierto para siempre'], en: ['Close the order: keeps deliveries and releases the rest without voiding', 'Cancel: voids the delivered part too', 'Leave it open forever'], de: ['Schließen: behält Lieferungen, gibt Rest frei', 'Stornieren: anulliert auch Lieferungen', 'Für immer offen lassen'] },
      correct: 0,
      why: { es: 'Cerrar respeta la parte ya entregada y su asiento; cancelar generaría un espejo que contradice la realidad física.', en: 'Closing respects the delivered part and its postings; cancelling would create a mirror contradicting physical reality.', de: 'Schließen respektiert Lieferung und Buchung; Storno widerspräche der Realität.' },
      prin: [{ es: 'Respetar lo ya sucedido', en: 'Respect what already happened' }, { es: 'Anular siempre es más limpio', en: 'Cancelling is always cleaner' }, { es: 'Congelar y olvidar', en: 'Freeze and forget' }], prinOk: 0,
      senior: [{ es: 'Verifica cantidades abiertas reales por línea', en: 'Verify real open quantities per line' }, { es: 'Comprueba que ningún documento destino pendiente enlaza al pedido', en: 'Check no pending target document links to the order' }, { es: 'Cierra y documenta la razón comercial', en: 'Close and record the business reason' }],
      dwhy: { es: ['Cancelar contradice las entregas ya contabilizadas y su COGS.', 'Dejarlo abierto mantiene stock comprometido fantasma que el MRP intentará servir.', 'Cerrar es la única acción coherente con la historia ya escrita.'], en: ['Cancelling contradicts deliveries already posted with their COGS.', 'Leaving it open keeps phantom committed stock that MRP will try to serve.', 'Closing is the only action consistent with history already written.'], de: ['Storno widerspricht gebuchten Lieferungen.', 'Offen lassen erzeugt Phantombestand für MRP.', 'Schließen passt zur bereits geschriebenen Geschichte.'] },
      hints: { es: '¿Qué pasa con el stock comprometido de las líneas no entregadas?' }
    }
  }),
  sk(0, 5, {
    t: { es: 'Fechas del documento', en: 'Document dates', de: 'Belegdaten' },
    o: { es: 'Dominar el trío de fechas (contabilización, vencimiento, entrega) y sus efectos.', en: 'Master the date trio (posting, due, delivery) and their effects.', de: 'Das Datumsdreieck (Buchung, Fälligkeit, Lieferung) beherrschen.' },
    c: { es: 'La fecha de contabilización decide periodo y asiento; la de vencimiento mueve la cobranza; la de entrega gobierna la logística: tres palancas distintas en cada documento.', en: 'The posting date drives period and entry; the due date drives collections; the delivery date drives logistics: three distinct levers per document.', de: 'Buchungsdatum steuert Periode, Fälligkeitsdatum Mahnung, Lieferdatum Logistik.' },
    m: { es: 'Cada fecha tiene un dueño distinto: contable, financiero, logístico. Nunca una por otra.', en: 'Each date has a different owner: accounting, finance, logistics. Never one for another.', },
    p: { es: 'En SYN-INV-0004, predice el efecto de mover cada fecha un mes.', en: 'On SYN-INV-0004, predict moving each date by one month.', de: 'Sage bei SYN-INV-0004 die Wirkung jeder Datumverschiebung voraus.' },
    v: { es: 'Comprueba periodo abierto y política antes de aceptar una fecha retroactiva.', en: 'Verify open period and policy before accepting a backdated date.', de: 'Prüfe offene Periode und Richtlinie für Rückdatierung.' },
    vs: [{ es: 'Identifica las tres fechas', en: 'Identify the three dates' }, { es: 'Asigna el efecto de cada una', en: 'Assign each one’s effect' }, { es: 'Valida periodo y política', en: 'Validate period and policy' }],
    r: { es: 'Fechar atrás para «arreglar» un cierre contable es fraude de periodo, no corrección.', en: 'Backdating to «fix» a closing is period fraud, not correction.', de: 'Rückdatierung für einen Abschluss ist Periodenbetrug.' },
    tips: { es: ['El informe de aging se construye sobre la fecha de vencimiento: moverla mueve la cobranza.', 'Document date ≠ posting date: la primera es comercial, la segunda contable.'], en: ['The aging report builds on the due date: moving it moves collections.', 'Document date ≠ posting date: the first is commercial, the second accounting.'] },
    pf: { es: 'Usar la fecha de entrega como fecha contable para «adelantar» ingresos.', en: 'Using the delivery date as posting date to «accelerate» revenue.' },
    d: { k: 'layers', cap: { es: 'Tres fechas, tres dueños', en: 'Three dates, three owners' }, n: [{ t: 'Contabilización', s: 'periodo + asiento' }, { t: 'Vencimiento', s: 'aging + cobro' }, { t: 'Entrega', s: 'logística' }] },
    a: {
      prompt: { es: 'Un comercial SYN quiere facturar con fecha del mes pasado para cumplir cuota. ¿Aceptas?', en: 'A SYN salesperson wants to post an invoice dated last month to hit quota. Do you accept?', de: 'Ein Verkäufer will mit Vormonatsdatum fakturieren. Akzeptierst du?' },
      opts: { es: ['No: la fecha contable refleja el hecho real; la cuota se gestiona fuera del sistema', 'Sí, si el periodo sigue abierto', 'Sí, cambiando el periodo manualmente'], en: ['No: the posting date reflects the real event; quota is managed outside the system', 'Yes, if the period is still open', 'Yes, by forcing the period'], de: ['Nein: Das Buchungsdatum spiegelt das Ereignis; Quote ist außersystemisch', 'Ja, bei offener Periode', 'Ja, Periode erzwingen'] },
      correct: 0,
      why: { es: 'El periodo abierto es una condición técnica, no un permiso ético: el asiento debe fecharse cuando nace el hecho económico.', en: 'An open period is a technical condition, not an ethical licence: entries are dated when the economic event occurs.', de: 'Eine offene Periode ist keine ethische Erlaubnis: Buchung zum Ereigniszeitpunkt.' },
      prin: [{ es: 'La fecha sigue al hecho', en: 'The date follows the event' }, { es: 'Técnico habilita, negocio decide', en: 'Technical enables, business decides' }, { es: 'El sistema es flexible', en: 'The system is flexible' }], prinOk: 0,
      senior: [{ es: 'Separa el problema comercial (cuota) del contable (fecha)', en: 'Separate the commercial problem (quota) from the accounting one (date)' }, { es: 'Verifica política de periodos y autorizaciones', en: 'Verify period policy and authorizations' }, { es: 'Ofrece la vía correcta: corregir la previsión, no el asiento', en: 'Offer the right path: fix the forecast, not the entry' }],
      dwhy: { es: ['«Periodo abierto» confunde posibilidad técnica con corrección contable.', 'Forzar el periodo requiere romper un control diseñado para impedir exactamente esto.', 'La fecha del hecho es el ancla de toda la cadena posterior: vencimiento, aging, impuestos.'], en: ['«Open period» confuses technical possibility with accounting correctness.', 'Forcing the period breaks a control designed to prevent exactly this.', 'The event date anchors the whole downstream chain: due date, aging, taxes.'], de: ['Offene Periode ≠ Korrektheit.', 'Erzwungene Periode bricht eine Kontrolle, die genau das verhindern soll.', 'Das Ereignisdatum verankert Fälligkeit, Aging, Steuern.'] },
      hints: { es: '¿Qué problema real intenta resolver el comercial y por qué no es este el camino?' }
    }
  }),
  sk(0, 6, {
    t: { es: 'Cadena documental', en: 'Document chain', de: 'Belegkette' },
    o: { es: 'Reconstruir la cadena base-destino de cualquier proceso B1 en ambas direcciones.', en: 'Reconstruct the base-target chain of any B1 process in both directions.', de: 'Die Basis-Ziel-Kette jedes Prozesses in beide Richtungen rekonstruieren.' },
    c: { es: 'Los documentos se copian unos de otros mediante enlaces base-destino: el pedido engendra la entrega, ésta la factura; cada enlace conserva cantidades y trazabilidad.', en: 'Documents copy into each other via base-target links: order begets delivery, delivery begets invoice; each link keeps quantities and traceability.', de: 'Belege erzeugen sich über Basis-Ziel-Verweise: Auftrag → Lieferung → Rechnung.' },
    m: { es: 'Nunca juzgues un documento aislado: pregúntale por su padre y sus hijos.', en: 'Never judge a document in isolation: ask for its parent and its children.', },
    p: { es: 'Sigue SYN-SO-0001 hasta su cobro y dibuja la cadena con cantidades abiertas.', en: 'Follow SYN-SO-0001 to its payment and draw the chain with open quantities.', de: 'Verfolge SYN-SO-0001 bis zur Zahlung und zeichne die Kette.' },
    v: { es: 'Comprueba que las cantidades abiertas de cada eslabón cuadran con la realidad.', en: 'Verify each link’s open quantities match reality.', de: 'Prüfe, dass offene Mengen je Glied der Realität entsprechen.' },
    vs: [{ es: 'Localiza el documento origen', en: 'Locate the source document' }, { es: 'Lista hijos y padres', en: 'List children and parents' }, { es: 'Cuadra cantidades abiertas', en: 'Reconcile open quantities' }],
    r: { es: 'Romper un eslabón a mano (borrar destino) deja al padre con cantidades fantasma.', en: 'Breaking a link by hand (deleting a target) leaves the parent with phantom quantities.', de: 'Ein manuell gebrochenes Glied hinterlässt Phantommengen.' },
    tips: { es: ['El mapa de flujo documental es tu mejor herramienta de diagnóstico: píntalo antes de tocar.', 'La cantidad abierta es la verdad del eslabón: no la cantidad original.'], en: ['The document flow map is your best diagnostic tool: draw it before touching.', 'Open quantity is the link’s truth: not the original quantity.'] },
    pf: { es: 'Mirar solo el último documento de la cadena y operar sobre él.', en: 'Looking only at the chain’s last document and operating on it.' },
    d: { k: 'chain', cap: { es: 'Oferta → Pedido → Entrega → Factura → Cobro', en: 'Quote → Order → Delivery → Invoice → Payment' }, n: [{ t: 'Pedido', s: '100 uds' }, { t: 'Entrega', s: '80 uds' }, { t: 'Factura', s: '80 uds' }, { t: 'Cobro', s: 'cierra' }] },
    a: {
      prompt: { es: 'SYN-INV-0009 muestra un total que no cuadra con lo entregado. ¿Dónde miras primero?', en: 'SYN-INV-0009 shows a total that does not match what was delivered. Where do you look first?', de: 'SYN-INV-0009 passt nicht zur Lieferung. Wohin schaust du zuerst?' },
      opts: { es: ['La cadena base-destino: qué entrega la originó y con qué cantidades', 'El total de la factura y lo recalculo', 'El maestro del cliente'], en: ['The base-target chain: which delivery originated it and with what quantities', 'The invoice total and recalculate it', 'The customer master'], de: ['Die Basis-Ziel-Kette: welche Lieferung, welche Mengen', 'Rechnungssumme nachrechnen', 'Kundenstammsatz'] },
      correct: 0,
      why: { es: 'El total hereda cantidades de la cadena: reconstruir el flujo revela si el problema nació aguas arriba.', en: 'The total inherits quantities from the chain: reconstructing the flow reveals whether the problem was born upstream.', de: 'Die Summe erbt Mengen aus der Kette: Flussrekonstruktion zeigt Ursprung.' },
      prin: [{ es: 'Río arriba antes que el delta', en: 'Upstream before the delta' }, { es: 'Aritmética primero', en: 'Arithmetic first' }, { es: 'Maestro primero', en: 'Master first' }], prinOk: 0,
      senior: [{ es: 'Abre el mapa de flujo del documento', en: 'Open the document flow map' }, { es: 'Compara cantidades por línea entre eslabones', en: 'Compare per-line quantities across links' }, { es: 'Localiza el primer eslabón donde el número deja de cuadrar', en: 'Locate the first link where the number stops matching' }],
      dwhy: { es: ['Recalcular el total solo valida la aritmética del último eslabón, no su origen.', 'El maestro del cliente no guarda cantidades de esta operación.', 'El primer desajuste de la cadena señala la causa raíz.'], en: ['Recalculating only validates the last link’s arithmetic, not its origin.', 'The customer master holds no quantities for this operation.', 'The chain’s first mismatch points at the root cause.'], de: ['Nachrechnen prüft nur das letzte Glied.', 'Der Stammsatz kennt keine Mengen.', 'Die erste Abweichung zeigt die Ursache.'] },
      hints: { es: '¿De dónde hereda sus cantidades esa factura?' }
    }
  }),
  sk(0, 7, {
    t: { es: 'Verificación basada en evidencia', en: 'Evidence-first verification', de: 'Nachweisbasierte Prüfung' },
    o: { es: 'Aplicar la disciplina de separar confirmado, probable, supuesto y no verificado antes de actuar.', en: 'Apply the discipline of separating confirmed, probable, assumed, and unverified before acting.', de: 'Bestätigt, wahrscheinlich, angenommen und ungeprüft trennen.' },
    c: { es: 'Toda afirmación sobre el sistema se clasifica por su evidencia: vista en pantalla, consultada en datos, reportada por otro, o supuesta; actuar exige subir de grado, no bajarlo.', en: 'Every system claim is graded by evidence: seen on screen, queried in data, reported by another, or assumed; acting requires moving up a grade, not down.', de: 'Jede Aussage wird nach Nachweis eingestuft; Handeln erfordert höhere Evidenz.' },
    m: { es: 'Cero conclusiones sin etiqueta de evidencia: es tu higiene profesional básica.', en: 'No conclusions without an evidence tag: your basic professional hygiene.', },
    p: { es: 'Toma una incidencia SYN y clasifica cada afirmación del ticket por grado de evidencia.', en: 'Take a SYN incident and grade every ticket claim by evidence level.', de: 'Stufe jede Aussage eines SYN-Tickets nach Evidenz ein.' },
    v: { es: 'Convierte cada supuesto en confirmado antes de proponer acción.', en: 'Convert every assumption into confirmed before proposing action.', de: 'Wandle jede Annahme in Bestätigung vor der Aktion.' },
    vs: [{ es: 'Lista las afirmaciones', en: 'List the claims' }, { es: 'Etiqueta cada una por evidencia', en: 'Tag each by evidence' }, { es: 'Decide la prueba mínima por supuesto', en: 'Decide the minimal test per assumption' }],
    r: { es: 'Presentar un supuesto como hecho en producción es la raíz de los desastres evitables.', en: 'Presenting an assumption as fact in production is the root of avoidable disasters.', de: 'Annahmen als Fakten sind die Wurzel vermeidbarer Katastrophen.' },
    tips: { es: ['Escribe el ticket con etiquetas: [Confirmado] [Probable] [Supuesto]. Cambia la conversación.', 'La prueba mínima vence a la prueba perfecta que nadie ejecuta.'], en: ['Write tickets with tags: [Confirmed] [Probable] [Assumed]. It changes the conversation.', 'The minimal test beats the perfect test nobody runs.'] },
    pf: { es: '«Lo vi en un sistema parecido» como evidencia suficiente.', en: '«I saw it in a similar system» as sufficient evidence.' },
    d: { k: 'gauge', cap: { es: 'Escalera de evidencia: supuesto → confirmado', en: 'Evidence ladder: assumed → confirmed' }, n: [{ t: 'Supuesto', s: 'grado 0' }, { t: 'Reportado', s: 'grado 1' }, { t: 'Consultado', s: 'grado 2' }, { t: 'Confirmado', s: 'actuable' }] },
    a: {
      prompt: { es: 'El usuario SYN dice «la factura desapareció». ¿Cuál es tu siguiente movimiento?', en: 'A SYN user says «the invoice disappeared». What is your next move?', de: 'Ein Benutzer sagt „Rechnung verschwunden“. Nächster Schritt?' },
      opts: { es: ['Buscar por número, socio, fechas, estado y series antes de concluir algo', 'Concluir que fue borrada y re-crearla', 'Reiniciar el servicio de la base de datos'], en: ['Search by number, partner, dates, status, and series before concluding anything', 'Conclude it was deleted and recreate it', 'Restart the database service'], de: ['Suche nach Nummer, Partner, Daten, Status und Serien', 'Als gelöscht annehmen und neu anlegen', 'Datenbankdienst neu starten'] },
      correct: 0,
      why: { es: '«Desapareció» es un reporte, no un hecho: la búsqueda estructurada lo convierte en confirmado (existe filtrado, cancelado, u otro periodo).', en: '«Disappeared» is a report, not a fact: structured search converts it into confirmed (filtered, cancelled, or another period).', de: '„Verschwunden“ ist ein Bericht, kein Fakt: strukturierte Suche schafft Gewissheit.' },
      prin: [{ es: 'Primero elevar la evidencia', en: 'Raise the evidence first' }, { es: 'Actuar para aprender', en: 'Act to learn' }, { es: 'Reiniciar resuelve', en: 'Restart fixes' }], prinOk: 0,
      senior: [{ es: 'Define qué buscarías exactamente y en qué orden', en: 'Define exactly what you would search and in what order' }, { es: 'Considera filtros de usuario y permisos como causa frecuente', en: 'Consider user filters and permissions as frequent cause' }, { es: 'Documenta el hallazgo con el número real del documento', en: 'Document the finding with the real document number' }],
      dwhy: { es: ['Re-crear duplica el asiento y destruye la trazabilidad si el original existía.', 'Reiniciar la base no cambia los datos: es un martillo para un tornillo inexistente.', 'La búsqueda estructurada es la única vía que produce evidencia.'], en: ['Recreating duplicates the entry and destroys traceability if the original exists.', 'A database restart does not change data: a hammer for a nonexistent nail.', 'Structured search is the only path producing evidence.'], de: ['Neuanlegen dupliziert die Buchung.', 'Neustart ändert keine Daten.', 'Nur die Suche erzeugt Nachweis.'] },
      hints: { es: '¿Qué explicaciones alternativas hay para «no la veo»?' }
    }
  })
];
